### ISSUE TITLE
the inference for three channel retina image

### ISSUE THREAD

**Issue by JiHooooo** [JJGO/UniverSeg#10]
Thanks for your good job and kindly sharing the inference code.
I found that the inference code is designed for single channel image. 
But the retina image, which exists in MegaMedical dataset and was used to train the model of UniverSeg, is always 3 channel.
Could you tell me how to processing those 3 channel image?

**Comment by VictorButoi** [comment]
For three channel images, we chose to convert them to greyscale first. We use something like this.

`
im_dir = # Your image dir
label_dir = # Your label dir

loaded_image = np.array(Image.open(im_dir).convert('L'))
loaded_label = np.array(Image.open(label_dir))
`

**Comment by JiHooooo** [comment]
Thanks for your explanation. I will try that,
