### ISSUE TITLE
Inquiry related to how to do testing with UniverSeg?

### ISSUE THREAD

**Issue by robotcv** [JJGO/UniverSeg#14]
Hello author, thank you for your work, after reading your work, I have the following questions, I hope to reply:
1) Is the final prediction result obtained by following "Getting Started"?
2) If I want to use your model to apply directly to other datasets such as ISIC2018, do I need to retrain it? Or can I just use the pre-trained model you provided?
3) What kind of threshold should I use for the output of Universeg to get the segmentation result with pixel value {0, 1} for each position?

**Comment by VictorButoi** [comment]
Greetings! Apologies for the late response, here are a few answers to your questions:

1. After you use the prediction code from "Getting started", you have to sigmoid the outputs. See the end of section 2 in the collab for an example.
2. I would try first with the pre-trained model, it might be good enough. Note that if the model was pre-trained with a support set size of 64 it will do best as you approach that number.
3. We have gone with the standard threshold of 0.5 after the sigmoid output, not tuned to particular tasks.

Hope this helps!

**Comment by robotcv** [comment]
Thank you very much for your response. Following your guidance, the prediction results are satisfactory.
