### ISSUE TITLE
Usage of ACDC, SCD, STARE, SpineWeb

### ISSUE THREAD

**Issue by xniu3** [JJGO/UniverSeg#18]
Hi there, I noticed that the paper mentioned that the datasets like ACDC, SCD, etc., are also being used in the project. Would you mind sharing the part of code of processing these datasets? Thank you very much.

**Comment by VictorButoi** [comment]
Sorry for being so slow on this, we are actively working on getting our pre-processing code up at the moment.

**Comment by xniu3** [comment]
Perfect! Thanks a lot for working on that I'm eagerly to see your awesome work :)
