### ISSUE TITLE
Using custom data

### ISSUE THREAD

**Issue by WangRongsheng** [JJGO/UniverSeg#2]
For a picture (from my own), how do I inference? Perhaps you could provide an example to show others how to apply it to their own images

**Comment by JJGO** [comment]
Sure thing, I tweaked the README a bit, the inference API is as follows

```python
from universeg import universeg

model = universeg(pretrained=True)

# To perform a prediction (where B=batch, S=support, H=height, W=width)
prediction = model(
    target_image,        # (B, 1, H, W)
    support_images,      # (B, S, 1, H, W)
    support_labels,      # (B, S, 1, H, W)
) # -> (B, 1, H, W)
```

We also provide a [Colab example](https://colab.research.google.com/drive/19Sauvhyzae5qvVLguaZRCuH1vJ5oTuw-?usp=sharing) that shows prediction with an open-access dataset.

**Comment by WangRongsheng** [comment]
good jobs! Thank you!

**Comment by marwanabb** [comment]
> Sure thing, I tweaked the README a bit, the inference API is as follows
> 
> ```python
> from universeg import universeg
> 
> model = universeg(pretrained=True)
> 
> # To perform a prediction (where B=batch, S=support, H=height, W=width)
> prediction = model(
>     target_image,        # (B, 1, H, W)
>     support_images,      # (B, S, 1, H, W)
>     support_labels,      # (B, S, 1, H, W)
> ) # -> (B, 1, H, W)
> ```
> 
> We also provide a [Colab example](https://colab.research.google.com/drive/19Sauvhyzae5qvVLguaZRCuH1vJ5oTuw-?usp=sharing) that shows prediction with an open-access dataset.

Hi @JJGO , the data formatting is very confusing for me, I don't understand  S=support, when I provide my custom data (following the colab tutorial) here's the error I get : 

![image](https://user-images.githubusercontent.com/117310221/233392357-5c928184-ab9a-4863-9c2d-60b5473f05be.png)

**Comment by JJGO** [comment]
In general, please create a new issue instead of following up on a closed one.

In your case S=144. The code fails because you are missing the batch dimension which is required as it's a PyTorch convention.

You can easily fix the issue by doing 

```python
image = image[None]
label = label[None]
support_images = support_images[None]
support_labels = support_labels[None]
```

Also ensure that pixel data is normalized to [0,1]

**Comment by JJGO** [comment]
Also, you should resize the image size to be (128,128) instead of (70,70)
