### ISSUE TITLE
OCTA image segmentation result is not good

### ISSUE THREAD

**Issue by zhouziyiaichifeiniu** [JJGO/UniverSeg#20]
Thanks for your kind words. So, the paper talks about UniverseG being pretrained on the OCTA500 dataset. But when I tried it on my own OCTA dataset, things didn't quite match up. And here's the kicker - when I cranked up the image batch-size to 50, the results were way worse than when it was less than 5. Any idea why that might be happening?

**Comment by adalca** [comment]
Could you show some results (inputs, outputs, context-sets) ? In what intensity range are your images?
