### ISSUE TITLE
meet a problem in model.py

### ISSUE THREAD

**Issue by sharonlee12** [JJGO/UniverSeg#21]
```
    def forward(self, target_image, support_images, support_labels):

        target = E.rearrange(target_image, "B 1 H W -> B 1 1 H W")
        print(f"support_images.size: {support_images.size()}")
        print(f"support_labels.size: {support_labels.size()}")
        support = torch.cat([support_images, support_labels], dim=2)

```

hello！I met a problem here,for 
`support = torch.cat([support_images, support_labels], dim=2)
RuntimeError: Tensors must have same number of dimensions: got 5 and 4`
I wish if anyone who can solve it

**Comment by adalca** [comment]
Hi @sharonlee12 , what those print statements output? Seems directly relevant!

**Comment by sharonlee12** [comment]
> Hi @sharonlee12 , what those print statements output? Seems directly relevant!

hello！sorry to reply so late,I have saved it and discovered that this is an issue with my dimension settings,Thank you for your reply!
