### ISSUE TITLE
results seems not good

### ISSUE THREAD

**Issue by sharonlee12** [JJGO/UniverSeg#22]
![image](https://github.com/JJGO/UniverSeg/assets/120789038/30ff67cd-1e92-4f4b-b68c-e757cb0a81ad)
![image](https://github.com/JJGO/UniverSeg/assets/120789038/84ccde02-71b4-4627-84e8-e41bf668f9d4)
Hello，result seems not good，

**Comment by jz5426** [comment]
no model is perfect
