### ISSUE TITLE
[Question] Data Organization of Processed Slices

### ISSUE THREAD

**Issue by xk-huang** [JJGO/UniverSeg#29]
(This is the following issue of https://github.com/JJGO/UniverSeg/issues/28)
 
I have another question about data storage organization of the processed slices.
 
In the supp., each task is defined as a quadra: `(Dataset, modality, single axis (if it is 3D else 1 axis), label)` and the hierarchical uniform sampling is applied in a five-stage approach: `dataset -> subject group -> acquisition modality -> axis -> label`.
Besides, there is another consideration about the organization of the `mid` and `max` slices.
(Also, is `subject group` the sample id?)
 
An intuitive method to store the data is to save them under paths like `dataset_name/subject_name/modality_name/axis/label`.
Given the consideration of the data splits, the paths are modified as `dataset_name/split_name/...` or `split_name/dataset_name/...`.
 
However, LMDB is used in UniverSeg to help improve I/O throughput.
I am not familiar with the tool. How is it implemented? Is `thunderpack` an instantiation?
I would guess it save the images and labels in a giant folder and track them with a single index file.
Or can I implement it with tools like `webdataset`? But I deem it hard as `webdataset` only supports sequential reading well.
 
This could raise another question of the implementation of the hierarchical uniform sampling. As I think the data organization method would affect the implementation of the sampling and inappropriate designs could easily bottleneck the I/O throughput during training.
 
Thanks again for your time and I am looking for your advice!

**Comment by VictorButoi** [comment]
Greetings. Thunderpack is a package that @JJGO wrote for insanely fast data-loading format when dealing with tons of individual files. https://github.com/JJGO/thunderpack. Let us know if you have any questions about it, it essentially is a way of construct KV stores that reduce the bottleneck from I/O.

**Comment by xk-huang** [comment]
Thanks for the speedy reply!
