### ISSUE TITLE
Training Script / Task Augmentation

### ISSUE THREAD

**Issue by souheib1** [JJGO/UniverSeg#30]
Hello ! 

I'm wondering if the training/task augmentation scripts will be released to the community. I'm having some problems reproducing the pipeline. 

Best regards,

**Comment by VictorButoi** [comment]
Greetings,

We don't really have any extensive augmentation scripts that are in good shape to be released, but I can point you towards two augmentation libraries that we found super useful:

- Kornia (bonus that it lets you augment on the gpu) https://github.com/kornia/kornia

- Albumentations https://albumentations.ai/
