### ISSUE TITLE
What is means of target_image, support_images, support_labels?

### ISSUE THREAD

**Issue by WangRongsheng** [JJGO/UniverSeg#4]

**Comment by JJGO** [comment]
Using the notation from the paper:

- `target_image` corresponds to $x^t$, i.e. the image you want to segment
- `support_images` are the $x$ entries of $S^t$, i.e. the images in the support set
- `support_labels` are the $y$ entries of $S^t$, i.e. the labels in the support set, that correspond to `support_images`
