### ISSUE TITLE
Bug in visualize_tensors function

### ISSUE THREAD

**Issue by kennyha85** [JJGO/UniverSeg#5]
What is **E** in `visualize_tensors` function?

``ax.imshow(E.rearrange(x,'C H W -> H W C'))``

**Comment by adalca** [comment]
We had a line

`import einops as E`

a bit lower down. We moved it higher up to avoid issues. 
`E` refers to [einops](https://einops.rocks/)

**Comment by JJGO** [comment]
Does this resolve your issue @kennyha85

**Comment by kennyha85** [comment]
> Does this resolve your issue @kennyha85

Yes, the issue has been solved
